name: Check for broken links
on: 
  workflow_dispatch:
  push: # for testing
  schedule:
    - cron:  '0 4 * * 0' # at 04:00 on sunday
jobs:
  link-check:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:

    - name: Check for broken links
      uses: ScholliYT/Broken-Links-Crawler-Action@21eab52f98097989d343116dbbd46dc4541b849b # v3.3.2
      with:
        website_url: 'https://opensource.muenchen.de'
        verbose: 'true'
        max_retry_time: 10
        max_retries: 2
        max_depth: 10
        connect_limit_per_host: 1
        always_get_onsite: 'true'
        exclude_url_prefix: |
          https://www.npmjs.com/search?q=%40muenchen,
          https://unsplash.com/de/,
          https://www.bsi.bund.de,
          https://www.bfdi.bund.de,
          https://www.gesetze-im-internet.de,
          https://github.com/it-at-m/opensource.muenchen.de
